// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwLmR_6r0CPKZrlzVyPA-_ZD4aLnhNXr0',
    appId: '1:470738266549:android:0cf9e9eea0aa8e7c3211fc',
    messagingSenderId: '470738266549',
    projectId: 'blood-types-77ce2',
    databaseURL: 'https://blood-types-77ce2-default-rtdb.firebaseio.com',
    storageBucket: 'blood-types-77ce2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRP7Zl10urd8CxFVNDj4N_YNnyVMGzUIE',
    appId: '1:470738266549:ios:60e0d43727fd5ea83211fc',
    messagingSenderId: '470738266549',
    projectId: 'blood-types-77ce2',
    databaseURL: 'https://blood-types-77ce2-default-rtdb.firebaseio.com',
    storageBucket: 'blood-types-77ce2.appspot.com',
    androidClientId: '470738266549-5j9iu6iv71bu1dm9jjfsi8f2k0kum2s6.apps.googleusercontent.com',
    iosClientId: '470738266549-r0l4q4cmp9btql2jco84dndr37731gk6.apps.googleusercontent.com',
    iosBundleId: 'com.example.testerApp',
  );
}
